### ISSUE TITLE
markdownサンプル範囲には登場しないがほかに対応したほうがよさそうなもの

### ISSUE THREAD

**Issue by kmuto** [kmuto/pandoc2review#11]
- SmallCaps : 手元のいろんなの食わせてみたけどどれも警告出ず。実際日本語系文章で使われてるんだろうかこれ…。Re:VIEWに対応するタグはない
- Image: なんかWordので出たような気がしたのだが。`//indepimage[ID]` にする
- Cite: 今はまじめにやらずにリテラルで。しかしまじめにやってるドキュメントがあるのかという疑問も…むしろ`@`が食われてよろしくないことのほうが多そう。
- Divは今はクラス名をそのままRe:VIEWブロック名 (`//NAME{`) に取るようにしている。キャプションもほしい？ (手元のいろんなのではあまり統一されている印象がない。#を使っていることが多いようだが…)

いずれにせよ完璧な変換は追求しない。

**Comment by niszet** [comment]
一応気づいたので、`Quoted`と`Underline`がreview.luaの中にはなさそうですね。`Underline`は割と新顔な気がします。

https://pandoc.org/lua-filters.html#type-underline

`Quoted`は`""`や`'`で囲われた文字列で（ターミナル上からやると外側の`'`が無効になってしまうが）

```
echo '"hoge"' | pandoc -t native
> [Para [Quoted DoubleQuote [Str "hoge"]]]

echo '"hoge"' | pandoc -t review.lua
> WARNING: Undefined function 'DoubleQuoted'
```

のように、現在は対応する関数がないのでごっそり抜けてしまいます。

**Comment by kmuto** [comment]
2ee910652 でQuoted, SmallCaps, Underline対応してみました。Imageはこれが出るドキュメントが結局見当たらず…。
SingleQuoted, DoubleQuotedはdeprecatedとなっているんですが、pandoc 2.11.3.1 だとむしろこれを指定しないと怒られますね。不思議…。

**Comment by niszet** [comment]
#12 の `-f markdown-smart`の指定によって、出力に`Quoted`は出なくなるようです。が、あって困るものではないのでそのままで…。

PandocのCustom Writerのコードを読んでみると、`SingleQuoted` や `DoubleQuoted` として呼び出していますね（これは意図しているものか聞いてみます）

https://github.com/jgm/pandoc/blob/b4b4e32307499aafa2e6c1c713ee41f1c787ea76/src/Text/Pandoc/Writers/Custom.hs#L141

`Image`は定義されているんですが、こちらはインライン要素を変換するコードになっています。

https://github.com/jgm/pandoc/blob/b4b4e32307499aafa2e6c1c713ee41f1c787ea76/src/Text/Pandoc/Writers/Custom.hs#L224

`CaptionedImage` の方はどうなっているかというと、段落要素`Para`のなかに`Image`要素だけがあるものが対象になっています。

https://github.com/jgm/pandoc/blob/b4b4e32307499aafa2e6c1c713ee41f1c787ea76/src/Text/Pandoc/Writers/Custom.hs#L121

なので、`![](lalune.jpg) aaa` とか `hoge ![](lalune.jpg)` のように、同じ行に他の要素が入っているとこのパターンに合わないので、`Image`が呼ばれるようです（コード書き換えて動作確認済み。実行時にWARNING出ないのがいやらしいですね…）

ですので、`Image`にはRe:VIEW側に段落中の画像ファイルに対する記法があればそれに変換する関数を書くことになると思います（Re:VIEWに詳しくないのでここまで…）

**Comment by kmuto** [comment]
ありがとうございます、Imageの挙動、わかりました。インラインは`@<icon>`を使っているので、それに割り当ててみます。

**Comment by kmuto** [comment]
documentedなものはだいたい対応したはずなのでcloseします。
