### ISSUE TITLE
Pandoc内部で特殊文字化したものを再変換するコードが必要

### ISSUE THREAD

**Issue by niszet** [kmuto/pandoc2review#12]
クォートの処理をしていて気付いたのですが、Pandocは内部で文字のコードを一旦変換しており、書き出し時に再度変換しているようです。対象となる文字はこのあたりに書かれています。

https://github.com/jgm/pandoc/blob/b4b4e32307499aafa2e6c1c713ee41f1c787ea76/src/Text/Pandoc/Writers/Shared.hs#L199-L214

`'`が`\8217`に変換されて出力されているので気づきました。この文字変換はFilterではなくWriter側で行う方が良いかなと思います。

**Comment by kmuto** [comment]
確かに'や--などが変化していますね。元からその文字の場合は変えたくないところですが、Writerにきたときに判別できるんでしょうか。

**Comment by niszet** [comment]
Twitterで@atusy氏と話して解決しました。`-f markdown-smart` のようにして、入力ファイルのmarkdownから `smart` extensionを無効にすれば良さそうです。お騒がせしました…。

**Comment by kmuto** [comment]
おぉ、ありがとうございます!

そういえばcode内や本文内は`\`を入れてもあまり気にしないけれども、#見出しの中だと`\`がいろいろわかりにくい挙動になるんですね。これも変換のせいなのかと思っていたら違いました…。

```
## \の場合 (わからなくはない)
echo "## \\" | pandoc -t native
[Header 2 ("section",[],[]) [LineBreak]]

## \Aの場合 (わからない…)
[Header 2 ("section",[],[]) [RawInline (Format "tex") "\\A"]]

## \\の場合 (わかる)
echo "## \\\\\\" | pandoc -t native
[Header 2 ("section",[],[]) [Str "\\"]]
```

**Comment by niszet** [comment]
Closedですがコメントだけ。
1つ目は行末にバックスラッシュを置くと強制改行（`LineBreak`）になる仕組み由来で、`-f markdown-escaped_line_breaks`を使うと`LineBreak`は`Str "\n"` になります。

https://pandoc.org/MANUAL.html#paragraphs

2つ目はTeXのコマンドを埋め込む、`raw_tex`のextension由来です。`-f markdown-raw_tex` で無効化出来ます。
https://pandoc.org/MANUAL.html#extension-raw_tex

3つ目はこちらだと再現できず（多分入力しているのは`\\\\`が正しい？）
