### ISSUE TITLE
Rawのformatのチェック

### ISSUE THREAD

**Issue by niszet** [kmuto/pandoc2review#18]
ちょっと機能が増えてきたので、やはり`Raw`についてはformatをチェックした方がよいかなと思います。

https://github.com/kmuto/pandoc2review/blob/main/review.lua#L434

`format`が`review`であれば、Re:VIEWのコード片がそのまま来たものとして埋め込む、という程度で良いと思います（他のフォーマットでも`Raw`のコードの正当性はチェックしていません（書いた人が責任もって正しいコードを埋め込む）ので。）

**Comment by niszet** [comment]
他に、`format`が`tex`であった場合、Pandoc's Markdownの`raw-tex` extensionを活かして（TeXのコマンドを埋め込めるので）それを適切に処理してRe:VIEWの出力に埋め込める処理を施す、というのもありかもしれません。上手く実装できると便利そうです。

他にも`raw_html`が有効になってるので、htmlタグも標準でPandoc's Markdownは受け付けます。

```
echo "<br>" | pandoc -t native
[Para [RawInline (Format "html") "<br>"]]
```

Re:VIEW側はこの辺りの記法が対応しそうですね。

https://github.com/kmuto/review/blob/master/doc/format.ja.md#%E7%94%9F%E3%83%87%E3%83%BC%E3%82%BF%E8%A1%8C

**Comment by kmuto** [comment]
ありがとうございます。

- A. 何かのドキュメント(主にmdかdocx)をともかくre化して作業する必要があり、固有rawも欠落がないようそのまま出してほしい。(主に私のユースケース)
- B. mdをマスターデータとして使い続ける際のRe:VIEWにそのまま食わせる際の拡張構文に使いたい。

のユースケースが競合するなぁと悩んでいました。

生データ自体についてはたしかにRe:VIEWの@<embed>、//embedにするのが妥当そうな感じがします。

**Comment by niszet** [comment]
Twitterから転記します

Re:VIEWで対応している「html」「latex」「idgxml」「markdown」「top」はRaw記法が来た時はembedに変換、他はスルー、で良いかもしれません（reviewを追加しても良いですが）

Raw記法は出力先フォーマットの記法をその場所に入れたいという用途なので、他の形式の場合を残す必要はないのではないかなぁと思っていますが（Bの用途ですね）、とにかく全部残すモードがあっても良いかもしれないですね。

docxにはraw記法がないので、基本的にはmarkdownスタートだけ考えればよいのかなぁ…とも思っています。

**Comment by kmuto** [comment]
ありがとうございます、考えてみます!

**Comment by kmuto** [comment]
#34 を作ってみました。任意のrawを作る方法がよくわかっていない…

**Comment by kmuto** [comment]
#34 を入れました
