### ISSUE TITLE
PlainとParaは挙動を合わせておくべき（？）

### ISSUE THREAD

**Issue by niszet** [kmuto/pandoc2review#19]
他のフォーマットのWriterでは概ね`Para`と`Plain`は同じ挙動になるようにされています。

`BullerList`などでLooseかtiteかで`Para`や`Plain`が呼ばれたり呼ばれなかったりするので合わせておいた方が変な挙動に悩まなくて良いかなと思います。

**Comment by kmuto** [comment]
ありがとうございます、とりあえずPlainをParaと同じ実装にしてみます。
