### ISSUE TITLE
見出しIDの利用

### ISSUE THREAD

**Issue by kmuto** [kmuto/pandoc2review#2]
```
## ヘッダ {#foo}
```

を

```
=={foo} ヘッダ
```

のように展開してあげたいが、Headerのattr.idを見ると、IDの明示指定していないときには空ではなく見出し内容を流用&重なったら採番付きというものが入ってしまっている。文字列で判断は困難なので、pandoc側でID指定していないときは空にしておくことはできるか？

**Comment by atusy** [comment]
IDの自動付与を防ぐには、

```
pandoc -f markdown-auto_identifiers
```

するしかない気がします。

https://pandoc.org/MANUAL.html#extension-auto_identifiers

**Comment by kmuto** [comment]
ありがとうございます! 確かにID自動付与をdisableにできました。
IDがコピーっぽかったら `-f markdown-auto_identifiers` を付けて再実行を呼びかける警告を出すようにしようかと思います。

**Comment by kmuto** [comment]
nestedの対応でフィルタも指定する必要が出てオプションが結局長くなるのは避けられないので、 `-f markdown-auto_identifiers` を一連の書式として使え、ということにします。
