### ISSUE TITLE
//sourceの実装

### ISSUE THREAD

**Issue by atusy** [kmuto/pandoc2review#20]
`//source`と見做せる記法は3通り考えられます。どれがいいでしょう？

| | 記法 | コメント |
|:-|:-|:-|
|1| BlockQuote内のCodeBlock | 一番自然だがLuaフィルタが必要 |
|2| `source`クラスか`quote`クラスあたりを持つCodeBlock | 一番素朴？ |
|3| `source`クラスを持つDiv | 足りない記法はDivで補うのが一般的ではある |

**Comment by niszet** [comment]
直感的には2かなぁと。MarkdownのCodeBlockの記法はユーザに馴染みが深いという点から。

**Comment by kmuto** [comment]
Re:VIEWの場合は基本的にユーザー任せではあるのですが、
個人的には`//source` は `//emlist` も `//list` も `//cmd` も使い済みでやむをえずさらに…というとき用、という設計の気持ちなので、2.が妥当かなと思いました。
また、今のところreview.luaのほうではLineBlockに相当するRe:VIEW命令がないので、代替として `//source` (config.lineblock)を割り当てています。

**Comment by atusy** [comment]
では2で行きます。
off topicですが、連続する半角スペースをそのまま出力する方法があれば、LineBlock実装できると思いますよ。等幅フォントな必要ないと思うので、pre formattedなparaくらいの実装にするとか。

**Comment by atusy** [comment]
`//source`のついでに`//cmd`も実装しても良いかもしれませんね。
`.cmd`クラスなら`//cmd`にする、みたいな。

ところで`//cmd`の用途ってなんでしょう？
コードブロックの言語に`sh`を指定するのと同等な気がするので気になりました。

**Comment by kmuto** [comment]
Re:VIEWの歴史的な事情ともともとの思想にあるのですが、

- 最初にタグ名から用途を表すものとして、//emlistや//cmdを作った。
- 言語オプションはコードハイライトのために追加された。
- そのため、言語オプションはRe:VIEWにとって用途を表すものではない。
- Re:VIEWの内部ロジック的にも言語を先に見て挙動を変えることはしていない。

実際の編集や組版出力を考えたときには、「命令1つ・オプションで用途切り替え」よりも「命令と用途が1対1」のほうが命令の数に伴う暗黙の用途制約もかけられるし、何かと都合がよいのでした。

**Comment by atusy** [comment]
@kmuto なるほど！ありがとうございます！
