### ISSUE TITLE
ドキュメント markdown-format.ja.md 中の段落の課題について

### ISSUE THREAD

**Issue by niszet** [kmuto/pandoc2review#28]
（課題別にissue分けます）

> 段落
> 複数行からなる英語文章を変換するとおかしな結果になります。(★)

これは `pandoc -f markdown+hard_line_breaks -t markdown+hard_line_breaks` で対応できます。`-t markdown`とすると改行文字位置には`\`が入ります。

`-t markdown+hard_line_breaks` の場合（入力もこの内容）

```
This is
a pen.
```

`-t markdown` の場合

```
This is\
a pen.
```

**Comment by niszet** [comment]
副作用の方が大きそうなので保留で…すみません。
ある程度しっかりやるなら、class指定して、子要素を見て`Str ""`か`Str "\n"か`LineBreak`へ置き換え処理をする…というのを各要素でやる、みたいなことになるのかなと思いました。

**Comment by kmuto** [comment]
ありがとうございます、要はこれSoftBreakの前後を見ればいいということですよね。

Luaでがんばるのは大変そうですし、どうせpandoc2reviewというRubyで包んでいるので、Lua側ではSoftBreakを代替文字にしておき、最終出力前にRubyで前後のUnicode文字種検証をして判断するという手段を考えています。

**Comment by atusy** [comment]
↓が`foo bar`にならず`foobar`になることを問題視してる感じですか？

```
echo -e 'foo\nbar' | pandoc example.md -t review.lua
# foobar
```

**Comment by kmuto** [comment]
そうですね。かといって日本語のところでスペースが入るのも困るというかんじです。

**Comment by atusy** [comment]
SoftBreakは半角スペースを返すようにして、`markdown+east_asian_line_breaks`にしとくのが良いと思います。

```md
あ
い
a
b
```

が

```
あい a b
```

になります

**Comment by kmuto** [comment]
ほうーそのようなものが!

**Comment by kmuto** [comment]
なるほどー… 欧文のみ or 和文のみはよさそうなのですが、和欧はできればあまり入れたくないところ(InDesign DTPなどのケースだとわりと邪魔)なので、汚くはなりますがRubyのunicode-eawで後処理にしようかな…と思います。
選択できるようにしておこうかな。

**Comment by atusy** [comment]
```
あいa b
```

になって欲しいってことですよね。これ私も思ってました。Luaフィルタでできないかちょっと調べてみます。

**Comment by kmuto** [comment]
Rubyで後処理する場合を #29 にしてみました。
pandoc2review-lib.rbのsoftbreakメソッドがこの処理をしていますが、ルールとしては https://drafts.csswg.org/css-text-3/#line-break-transform をベースにしつつ、このルール3はいまいちなので、よりスペースを入れない単純化したものにしています(Re:VIEWでeaw機能を有効にしたときに使うルールをコピーしています)。

**Comment by atusy** [comment]
そういえばRe:VIEW側でも段落内の改行って処理してくれますよね？
それならSoftBreakは\nで吐いておけばeast_asian_linebreaksとかeawいらないですね。

**Comment by kmuto** [comment]
このツールの根幹目的として「何かから編集作業しやすいreを作る」というのがあって、そのときに1段落は1行でないと、表記統一などですごく扱いにくいんですよね(編集前にまずその作業をするところから始めるくらい)。
また、Re:VIEWでは段落については確かに結合処理はするのですが、箇条書きや表の中など「行」でしか見ないものがあるので、能率性・安全性の観点からpandoc段階で1段落1行形式にしておきたいのでした。

**Comment by atusy** [comment]
@kmuto なるほど…！背景説明ありがとうございます。
