### ISSUE TITLE
コードリストキャプションの対処

### ISSUE THREAD

**Issue by kmuto** [kmuto/pandoc2review#3]
CodeBlockにキャプションが渡されないが、そもそもMarkdown/Pandocにコードリストのキャプションを指定する方法はある？

**Comment by atusy** [comment]
こんな感じで、attributeとしてcaptionを持たせることはできます。
captionをどう扱うかはLuaで定義しなければなりませんね。

````
```{caption='caption of foo'}
foo
```
````

caption内でのmarkdown記法を使うには、captionを`pandoc.read`に渡してAST化します。
https://pandoc.org/lua-filters.html#pandoc.read

**Comment by kmuto** [comment]
おぉ、ありがとうございます。
実際のところバラバラなmdからともかくそれっぽく変換できればよいので、caption=''のみで考えます!
