### ISSUE TITLE
LineBreakは改行でなく@<br>{}?

### ISSUE THREAD

**Issue by kmuto** [kmuto/pandoc2review#33]
pandoc Markdown仕様を見ていたら、LineBreakは単なる改行というより、段落途中での強制改行なんですね。
となると、`\n`じゃなくて`@<br>{}`にしておいたほうがよいのかな。
副作用がある？

**Comment by atusy** [comment]
それが正しい気がしますね。

**Comment by kmuto** [comment]
はいー、ではbrにしときますね。

**Comment by kmuto** [comment]
今の//beginchild実装で`@<br>`が入ってしまってテストがこけるので、そのあたりのテストはいったんコメントアウトしています(というかテスト内容も「あるべき姿」になっていないですが)。
