### ISSUE TITLE
Pandoc < 2.4のサポート拡充

### ISSUE THREAD

**Issue by atusy** [kmuto/pandoc2review#35]
Custom Writerの`PANDOC_DOCUMENT.meta`はPandoc >= 2.4が必要。
Pandocのバージョンが古い場合はLuaフィルタを使ってRe:VIEWなRawBlockを吐く手がありそうです。
ここまでする必要があるかはさておき。

**Comment by kmuto** [comment]
来年にはDebian stableが更新されて、pandocも最低2.9にはなると思うので、必須機能以外はまぁよいかな…と思います。

**Comment by atusy** [comment]
お、そうなんですね！じゃあとりあえずCloseしちゃいますか。
