### ISSUE TITLE
ブロック命令の対応

### ISSUE THREAD

**Issue by kmuto** [kmuto/pandoc2review#37]
今はDivをシンプルに
```
//クラス名{
内容
//}
```
にしている。

## 1行命令に対応したい

- `<div class="noindent" /> → //noindent`
- `<div class="blankline" /> → //blankline`

`<div></div>`でもいいけど。MarkdownのDiv判定ってどうなってるんだっけか…

## キャプション付きに対応したい

//note, //memo, //tip, //info, //warning, //important, //caution, //notice は `//note[caption]{` のようにキャプションをとることがある。

- 最初の行が見出しならそれを使う？ (この場合はRuby側で後加工するのがよさそう)
- caption=属性を見る？ (luaで済むが、コンテンツ側がそういう書き方(ユースケース2)をしてないとダメ)

**Comment by atusy** [comment]
# 1行命令

## noindent

1行命令のために空Divを使うのは読みにくい気がします。
たとえば↓みたいに、noindentと段落の間に空行が入るため。

```
::: {.noindent}
:::

foo
bar
```

もしDivを使うなら、

```
::: {.noindent}
foo
bar
:::
```

を

```
//noindent
foo bar
```

にする感じでしょうか。

## blankline

Pandocだと強制改行を`\`で表現できるので、

```
foo \
\
bar
```

を

```
foo

//blankline

bar
```

にする方がいいのかな?と思います。
これならLuaフィルタで対応できますね。

# キャプション付

個人的にはクラス付きHeaderが使いたいですね。
ただ、`<div>`もDiv扱いなので、非Pandocユーザー向けにはDiv+Header記法かcaption属性付きDivが良いと思います。

````bash
$ echo '<div>foo</div>' | /usr/local/bin/pandoc -f markdown -t native
[Div ("",[],[])
 [Plain [Str "foo"]]]
````

Div+Header記法ならキャプションにマークダウンも使えるのはいいですね。
Luaフィルタでも対応できます。

**Comment by kmuto** [comment]
> # 1行命令
> ## noindent
> 1行命令のために空Divを使うのは読みにくい気がします。
> たとえば↓みたいに、noindentと段落の間に空行が入るため。
> 
> ```
> ::: {.noindent}
> :::
> 
> foo
> bar
> ```

そうですね、たしかに…。続く段落を対象にしていることは自明で、あまり囲みたくはないので、むしろspanに近いでしょうか。

> ## blankline
> Pandocだと強制改行を`\`で表現できるので、
> ```
> foo \
> \
> bar
> ```
> 
> を
> 
> ```
> foo
> 
> //blankline
> 
> bar
> ```
> 
> にする方がいいのかな?と思います。
> これならLuaフィルタで対応できますね。

これはいいですね、スマートに思います!

> # キャプション付
> 個人的にはクラス付きHeaderが使いたいですね。
> ただ、`<div>`もDiv扱いなので、非Pandocユーザー向けにはDiv+Header記法かcaption属性付きDivが良いと思います。
> 
> ```shell
> $ echo '<div>foo</div>' | /usr/local/bin/pandoc -f markdown -t native
> [Div ("",[],[])
>  [Plain [Str "foo"]]]
> ```
> 
> Div+Header記法ならキャプションにマークダウンも使えるのはいいですね。

ですです。みんな見出しにカジュアルにインラインを入れてくるんや…

> Luaフィルタでも対応できます。

おぉ…

**Comment by atusy** [comment]
noindentについてはLaTeX記法を借用するって手もありますね。
`\noindent` -> `//noindent`にする感じです。
直後のSoftBreakを`\n`に変換しないといけないので、Luaフィルタ案件ではあります。

```
echo '\\noindent\nfoo' | pandoc -t native 
[Para [RawInline (Format "tex") "\\noindent",SoftBreak,Str "foo"]]
```

**Comment by atusy** [comment]
キャプション付はDiv内にcaption属性が良い気がしてきました。HTMLの`<div>`タグ使えば非Pandocユーザーにも十分使えると思います。
Luaフィルタ使えばcaptionをmarkdown扱いしてパースすることもできます。

先頭のヘッダをキャプションにしてしまうと、ユーザー的に想定外な挙動にも見えそうです。
キャプション化したくない場合は

- Div内にcaption属性
- 先頭をコメントにする

といった変な書き方を駆使する必要が出てきます。

**Comment by kmuto** [comment]
なるほど、どっちもその方針でよさそうに思いました。
テストユニットのほう変えときますね。

**Comment by kmuto** [comment]
キャプションにインライン使えない、という問題は残りはするけど、まぁいいかな…。

**Comment by kmuto** [comment]
必要なのひととおり解決しちゃった…
ブラボー @atusy さん!
