### ISSUE TITLE
Strongの対処

### ISSUE THREAD

**Issue by kmuto** [kmuto/pandoc2review#4]
`___STRONG___` は、`@<b>$@<i>{STRONG}$` を作ってしまう。
Re:VIEWに`@<bi>`はないのでそもそもどうしようという話ではあるが、b+iであることをLuaコード内で検知する方法はあるか？

**Comment by atusy** [comment]
Luaフィルタなら検知できますね。検知してどんな出力にしたいか教えて頂ければPRしますよ。

**Comment by kmuto** [comment]
b+iがRe:VIEW側で想定していないのですが、ひとまずの代替として

`___STRONG___`, `***STRONG___`
↓
`@<strong>{STRONG}`

がよいかなと考えています。filterではインラインタグについてはsurround_inline処理で`{}`囲みを使いたくないときの対応をいろいろしていますが、`___`はあまり見かけないタグですし、その対処まではしなくてもよいかと思っています。

あるいはWriterで `function StrongEmph(s)` としてさわれるようなものをフィルタで作る、というのはできるのでしょうか。

**Comment by niszet** [comment]
@atusy 氏がさくっと解決してくれそうなのでコメントだけ…

現時点ではPandocのフィルタは新しいデータ型をつくれないので、この場合は`Span`に適当なクラス（`.strong`など）を持たせて、Writer側は`function Span(e)`内でclassを見て処理、となると思います（割とこの方法でやることが多い）

今は下記のように`Strong`の中に`Emph`が入る形だけど、仕様として明記されている挙動ではなかったはずなので逆順の場合で入ってる場合も置き換えるLuaフィルタを入れるのが良さそうかなと思います。

```sh
echo ***STRONG*** | pandoc -t native
[Para [Strong [Emph [Str "STRONG"]]]]
```

**Comment by atusy** [comment]
PR #13 で対応できてるはずですー
