### ISSUE TITLE
HorizontalRuleの対処

### ISSUE THREAD

**Issue by kmuto** [kmuto/pandoc2review#5]
`//hr` としているが、オフにするオプションがほしい。
オプションはmdファイルのメタ情報から入れる方法があるようだが、コマンドラインかYAMLからはいけるか？

**Comment by niszet** [comment]
コマンドラインからは `-M` (`--metadata`)で、

https://pandoc.org/MANUAL.html#option--metadata

YAMLなら

https://pandoc.org/MANUAL.html#extension-yaml_metadata_block

で、任意のKEY（と必要に応じてVALUE）を指定してあげて、メタデータから拾ってくることになると思います（Writerで拾えないならFilterで前処理して`Null`を返すなど）

https://pandoc.org/lua-filters.html#meta

**Comment by kmuto** [comment]
ありがとうございます! Writerからだと`PANDOC_DOCUMENT`が古いpandocバージョンでは使えず、metaが取れなくてしばらく苦戦していました。
もうあきらめて新しいpandoc使えにしよう、という気持ちになりました!

**Comment by kmuto** [comment]
43e1d9d で(`PANDOC_DOCUMENT`が使える環境なら)metaからのロードを実装しました。
