### ISSUE TITLE
pandoc 3以降対応

### ISSUE THREAD

**Issue by kmuto** [kmuto/pandoc2review#59]
現状pandoc 3系で動かない

- PANDOC_DOCUMENTがなくなったので、-Mなどで情報を引き渡せなくなっている。
- ノード単位のシンプルなやり方はまだあるけれども、クラシックスタイル扱いになっていて、いつか削除するかもらしい。https://pandoc.org/custom-writers.html#changes-in-pandoc-3.0
- https://github.com/jgm/djot.lua/blob/main/djot-writer.lua を参考に関数型で書き換える方法をやってみているが、el.contentの扱いなどがはるかに難しくなっていて途方…

**Comment by atusy** [comment]
時間あるとき見てみます！

**Comment by kmuto** [comment]
対応いただいたのでcloseします
