### ISSUE TITLE
見出しレベルの開始値の変更

### ISSUE THREAD

**Issue by kmuto** [kmuto/pandoc2review#6]
今は`#`の数にしているが、mdファイルが節単位になっていることがしばしばあるため、コマンドラインかYAMLで見出し初期レベル値を指定できるとよさそう。
渡せればあとはHeader関数内で処理すること自体は簡単。

**Comment by niszet** [comment]
Pandocの方から来ました。

入力ファイル側の話であれば、`--shift-heading-level-by` オプションがあるのでこれをつかえばよいかもしれません。

https://pandoc.org/MANUAL.html#option--shift-heading-level-by

**Comment by kmuto** [comment]
情報ありがとうございます、
手元(Debian stable)のpandocバージョンが古すぎたので、新しいバージョンで試してみたところうまく動きました!
確かにこれで十分な感じです。
