### ISSUE TITLE
ラップスクリプトを作る?

### ISSUE THREAD

**Issue by kmuto** [kmuto/pandoc2review#9]
オプションがいろいろ長くなりそうなのとフィルタ類のパスの問題があるので、wrapするシェルスクリプトか何かを作ったほうがよさそう。

**Comment by niszet** [comment]
Pandoc 2.8以降の機能になりますが、@sky_y 氏の記事にあるようなデフォルトファイルを使うことも選択肢に入るかなと思います。設定をまとめておくファイルです。

[Pandoc 2.8 新機能] 長いオプションをファイルにまとめるDefault file
https://qiita.com/sky_y/items/b243c2618706605e5fdd

**Comment by kmuto** [comment]
ありがとうございます。デフォルトファイル機能だとwriter/filterのセットが別フォルダにある場合の処理にはやはり難しいのかなと思いました。
呼び出しスクリプトと同じフォルダ(かそのサブフォルダ)にあるwriter/filterファイルを使ってカレントフォルダに適用する、というユースケースを想定しており、
`pandoc -t <どこか>/review.lua --lua-filter <どこか>/nestedlist.lua  file` で、`<どこか>` はユーザーの環境によるというシーンだと、同定するには`<どこか>`と同じところにあるスクリプトから呼び出す以外難しそうな気がしています。

**Comment by niszet** [comment]
なるほど…。ちょっと手元で試してみましたが、デフォルトファイル中に`<どこか>`を書かないといけないので、`<どこか>`を自由に設定できるようにしたいとすると難しいですね（pandocを実行したディレクトリを起点としていて、デフォルトファイルを`<どこか>`に置いてもそのディレクトリは探してくれない模様…）
`<どこか>`を`review`などディレクトリ名固定にしても良いかなとは思いますが…。もう少し良い方法ないか考えてみます。

**Comment by kmuto** [comment]
ラップするスクリプトとしてpandoc2review.rbを作って入れてみました。
このスクリプトと同じところにluaを入れておけば絶対パスでそれを使うようになっています。

ということでこのissueについては(pandocだけで完結はしませんが)closeできそうです。
